# -*- coding: utf-8 -*-
"""modeling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMA0jBaG0ktftzMH-4n-rnyPQu9kWvia
"""


import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import mlflow
import joblib

mlflow.autolog()

def train_model():
    
    if not os.path.exists('tourism_preprocessing.csv'):
        raise FileNotFoundError("Berkas tourism_preprocessed.csv tidak ditemukan! Silakan unggah terlebih dahulu.")

    df = pd.read_csv('tourism_preprocessing.csv')

    
    X = df.drop(columns=['Category_Encoded'])
    y = df['Category_Encoded']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print("Memulai pencatatan eksperimen ke MLflow...")
    with mlflow.start_run(run_name="Random_Forest_Basic"):
        
        model = RandomForestClassifier(random_state=42)
        model.fit(X_train, y_train)

        
        train_acc = model.score(X_train, y_train)
        test_acc = model.score(X_test, y_test)

        print(f"Model berhasil dilatih!")
        print(f"Akurasi Data Training: {train_acc:.4f}")
        print(f"Akurasi Data Testing : {test_acc:.4f}")


if __name__ == "__main__":
    train_model()