name: Machine Learning CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/tourism_preprocessed.csv"
  TARGET_VAR: "Credit_Score"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo $CSV_URL

      # - name: Install MLflow and Dependencies
      #   run: |
      #     pip install mlflow scikit-learn pandas
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Run MLflow Project Re-training
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          mlflow run MLProject --env-manager local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Save mlruns to repo
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git pull
          git add -f mlruns/
          git commit -m "Save mlruns from CI run" || true
          git push origin main
      # - name: Upload MLflow Runs Artifacts to GitHub Repository
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mlflow-tracking-artifacts
      #     path: mlruns/ # Mengambil langsung seluruh folder log eksperimen & model dari MLflow
      #     retention-days: 90
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "eksperimen-sml-chellyne" 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Tag Docker Image
        run: |
          docker tag eksperimen-sml-chellyne ${{ secrets.USERNAME }}/eksperimen-sml-chellyne:latest
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.USERNAME }}/eksperimen-sml-chellyne:latest
